Controllers/PostsController.cs
using HisserFullStack.Data.Services;
using HisserFullStack.Data.Static;
using HisserFullStack.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace HisserFullStack.Controllers
{
    [Authorize]
    public class PostsController : Controller
    {
        private readonly IPostsService _service;

        public PostsController(IPostsService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allPosts = await _service.GetAllAsync(n => n.User);
            return View(allPosts);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allPosts = await _service.GetAllAsync(n => n.User);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allPosts.Where(n => n.Title.Contains(searchString) || n.Description.Contains(searchString)).ToList();
                return View("Index", filteredResult);
            }

            return View("Index", allPosts);
        }

        //Get: Posts/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewPostVM postVM)
        {
            if (!ModelState.IsValid)
            {
                return View(postVM);
            }

            var post = new Post
            {
                Id = postVM.Id,
                Title = postVM.Title,
                Description = postVM.Description,
                UserId = User.FindFirstValue(ClaimTypes.NameIdentifier)
            };

            await _service.AddAsync(post);
            return RedirectToAction(nameof(Index));
        }

        //Get: Posts/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var post = await _service.GetPostByIdAsync(id);
            if (post == null || !post.UserId.Equals(userId))
                return View("NotFound");

            var postVM = new NewPostVM
            {
                Id = post.Id,
                Title = post.Title,
                Description = post.Description,
            };

            return View(postVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewPostVM postVM)
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var post = await _service.GetPostByIdAsync(postVM.Id);
            if (id != postVM.Id || !post.UserId.Equals(userId))
            {
                return View("NotFound");
            }

            if (!ModelState.IsValid)
            {
                return View(postVM);
            }

            await _service.UpdatePostAsync(postVM);
            return RedirectToAction(nameof(Index));
        }

        //Get: Posts/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var post = await _service.GetPostByIdAsync(id);
            if (post == null || (!post.UserId.Equals(userId) && !userRole.Equals(UserRoles.Admin)))
                return View("NotFound");

            return View(post);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var post = await _service.GetPostByIdAsync(id);
            if (post == null || (!post.UserId.Equals(userId) && !userRole.Equals(UserRoles.Admin)))
            {
                return View("NotFound");
            }

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/NotFound.cshtml
<div class="row text-center">
    <div class="col-md-6 offset-3">
        <h1 style="color: #87DA2A;">You've reached the end of the internet</h1>
        <hr />
        <a class="btn btn-success" asp-controller="Posts" asp-action="Index">Home Page</a>
    </div>
</div>

Views/Shared/_Identity.cshtml
@using Microsoft.AspNetCore.Identity;

@inject UserManager<ApplicationUser> UserManager;

@if (User.Identity.IsAuthenticated)
{
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}
else
{
    <a class="btn btn-success my-2 my-sm-0" asp-controller="Account" asp-action="Login"> 
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register"> 
        <i class="bi bi-person-plus"></i> Register
    </a>
    <span style="padding: 5px;"></span>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HisserFullStack</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HisserFullStack.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>
<body style="background: #39274F;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background: #87DA2A;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Posts" asp-action="Index" style="color: #39274F;">Hisser</a>
                <!--<img src="~/Resources/HisserIcon.jpg" alt="logo">-->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="navbar-nav">
                            <a class="nav-link text-dark" asp-controller="Posts" asp-action="Index" style="color: #39274F;"> <i class="badge-info bi-card-text"></i> Posts</a>
                        </li>

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link drop-down-toggle" href="#" id="navbarDropdown" role="button" data-toggle="button" data-bs-toggle="dropdown"
                            aria-haspoppup="true" aria-expanded="false" style="color: #39274F;">
                                        <i class="bi bi-gear" style="color: #39274F;"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background: #39274F;">
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Users" style="color: #87DA2A;"> 
                                        <i class="bi bi-person" style="color: #87DA2A;"></i> Users</a>
                                </div>

                            </li>
                        }
                    </ul>

                    <form class="form-check-inline my-2 my-lg-0" asp-contoller="Posts" asp-action="Filter" style="padding-right: 25px; display:flex;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for post..." style="background: #39274F; color: #87DA2A;"/>
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="border-color: #39274F;"> <i class="bi bi-search" style="color: #39274F;"></i></button>
                    </form>

                    <partial name ="_Identity.cshtml" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background: #87DA2A;">
        <div class="container" style="color: #39274F;">
            &copy; 2022 - Hisser
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>